---
name: 🐞 Bug Report
about: Report a bug in the application
title: '[BUG] '
labels: bug
assignees: ''

---

## 🧩 Used Way
- [ ] SSE
- [ ] Python
- [ ] Built in mcpo

### If SSE, what type of call?
- [ ] Direct in Open WebUI (0.6.33+)
- [ ] External MCP server
  - Which one? _________

## 🖼️ Image Provider
- [ ] Pexels
- [ ] Sdui
- [ ] Unsplash
- [ ] None

## 🌿 Branch
- [ ] latest
- [ ] Dev-latest

## ✅ Checklist
- [ ] I have used the example prompt
- [ ] I have read the recommendations
- [ ] I have searched for open tickets

## 📝 Description
What is happening?

## 🔁 How to Reproduce
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '...'
3. Scroll down to '...'
4. See error

## 🎯 Expected Behavior
What should have happened?

## 📎 Logs & Screenshots
Attach any relevant logs, error messages, or screenshots here.
